/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package at.bestsolution.e4.addressbook.model.addressbook.validation;

import at.bestsolution.e4.addressbook.model.addressbook.AddressType;
import at.bestsolution.e4.addressbook.model.addressbook.Country;
import at.bestsolution.e4.addressbook.model.addressbook.FederalState;
import at.bestsolution.e4.addressbook.model.addressbook.Person;

/**
 * A sample validator interface for
 * {@link at.bestsolution.e4.addressbook.model.addressbook.Address}. This
 * doesn't really do anything, and it's not a real EMF artifact. It was
 * generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled
 * with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AddressValidator {
	boolean validate();

	boolean validateStreet(String value);

	boolean validateZip(String value);

	boolean validateCity(String value);

	boolean validateCountry(Country value);

	boolean validateFederalState(FederalState value);

	boolean validateType(AddressType value);

	boolean validatePerson(Person value);
}
