/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package at.bestsolution.e4.addressbook.model.addressbook.validation;

import at.bestsolution.e4.addressbook.model.addressbook.Country;

/**
 * A sample validator interface for {@link at.bestsolution.e4.addressbook.model.addressbook.FederalState}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FederalStateValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateCountry(Country value);
}
