/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package at.bestsolution.e4.addressbook.model.addressbook.validation;

import org.eclipse.emf.common.util.EList;

import at.bestsolution.e4.addressbook.model.addressbook.Address;
import at.bestsolution.e4.addressbook.model.addressbook.AddressBook;

/**
 * A sample validator interface for
 * {@link at.bestsolution.e4.addressbook.model.addressbook.Person}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateAddresses(EList<Address> value);

	boolean validateFirstname(String value);

	boolean validateLastname(String value);

	boolean validateAddressBook(AddressBook value);
}
