/*
* generated by Xtext
*/
package at.bestsolution.e4.jfx.xtext.ui.contentassist;

import at.bestsolution.e4.jfx.xtext.ui.contentassist.AbstractJFXCssProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JFXCssProposalProvider extends AbstractJFXCssProposalProvider {

}
