/*
 * generated by Xtext
 */
package at.bestsolution.e4.jfx.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JFXCssRuntimeModule extends at.bestsolution.e4.jfx.xtext.AbstractJFXCssRuntimeModule {

}
