/*
* generated by Xtext
*/
package at.bestsolution.e4.jfx.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JFXCssOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
