/*
* generated by Xtext
*/
package at.bestsolution.e4.jfx.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.e4.jfx.xtext.services.JFXCssGrammarAccess;

public class JFXCssParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JFXCssGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.bestsolution.e4.jfx.xtext.parser.antlr.internal.InternalJFXCssParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.e4.jfx.xtext.parser.antlr.internal.InternalJFXCssParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "JFXCss";
	}
	
	public JFXCssGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JFXCssGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
