/*
* generated by Xtext
*/
package at.bestsolution.e4.jfx.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JFXCssAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("at/bestsolution/e4/jfx/xtext/parser/antlr/internal/InternalJFXCss.tokens");
	}
}
