/*
 * generated by Xtext
 */
package at.bestsolution.e4.jfx.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JFXCssUiModule extends at.bestsolution.e4.jfx.xtext.ui.AbstractJFXCssUiModule {
	public JFXCssUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
